### ISSUE TITLE
Integration of metadata

### ISSUE THREAD

**Issue by willscott** [filecoin-project/motion#16]
current metadata is stored locally from put/get requests.

we should integrate so that these keys end up aligned with the singularity model for compatibility / eventual push into deals
```[tasklist]
### Tasks
- [x] Add structs for /status payload and return empty status until implemented
- [ ] Persistence through shared DB
- [ ] aligned on data model
```

**Comment by masih** [comment]
#31 completes the first task.

**Comment by TorfinnOlsen** [comment]
The "persistence" through sharedDB task, are we considering that part of figuring this out is also figuring out the tunnel to enable it's accessibility? I know Will has mentioned Argo a few times(having looked it up seems a good option). Curious if you had other plans or ideas you were going to pursue @masih?

**Comment by masih** [comment]
All metadata will be stored on Singularity. @willscott  Are you happy for this issue to be closed?

**Comment by willscott** [comment]
yep 👍
