### ISSUE TITLE
Testing with SPs

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/motion#175]
Engage and test with our list of SPs to test the deal making part and make sure it works as part of the complete motion experience.
- [x] Prepare test data of ~100GB
- [x] Make deals with test SPs
- [x] Test retrievals
```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/motion/issues/188
- [ ] https://github.com/filecoin-project/motion/issues/187
- [ ] https://github.com/filecoin-project/motion/issues/186
- [ ] https://github.com/filecoin-project/motion/issues/185
- [ ] https://github.com/filecoin-project/motion/issues/184
- [ ] https://github.com/filecoin-project/motion/issues/183
- [ ] https://github.com/filecoin-project/motion/issues/182
- [ ] https://github.com/filecoin-project/motion/issues/189
- [ ] https://github.com/filecoin-project/motion/issues/190
```

**Comment by rvagg** [comment]
Underway. This is the state of play as of today, waiting for sealing as far as I know, so we still have the data locally:

<img width="1364" alt="Screenshot 2023-11-06 at 3 45 54 pm" src="https://github.com/filecoin-project/motion/assets/495647/fc6a9436-dc3c-4a35-b665-a684f0a4fbcd">

We had a bit of trouble making deals but have sorted out some bugs along the way. Notably https://github.com/data-preservation-programs/singularity/pull/413 for proposing usable deals and https://github.com/data-preservation-programs/singularity/pull/416 for serving pieces; plus a couple of problems on the other side too but we seem to be good for now.

Next steps:

 1. [ ] Sealing all these pieces
 2. [ ] Performing and measuring some baseline retrievals
 3. [ ] Deploying and measuring @gammazero's retrieval fixes

I'll hopefully get some basic work for 2 done today. We have a record (from the https://github.com/filecoin-project/motion-sp-test status.json file) of files we've stored, their UUID mapping, their size and SHA2-256 digest so we can do some retrievals with different size blobs and confirm we get what we expect. We could even toy around with streaming videos out of Motion for demonstration purposes I think.

**Comment by rvagg** [comment]
Going to call this one done and write up the learnings; it didn't end up being as methodical as hoped but what we learned should help us start a new iteration of testing, with existing and new SPs.
