### ISSUE TITLE
Enable Use of Client AWS keys and add instructions to readme

### ISSUE THREAD

**Issue by TorfinnOlsen** [filecoin-project/motion#41]
As an ISV, I want to be able to use my own AWS keys for the provided S3 Connector, so that I can securely leverage the S3 Connector to test storage on the Motion API.

```[tasklist]
### Tasks
- [ ] Enable user to incorporate their own credentials(this possibly can already be done by replacing the key flags hard coded into the connector as presently built) need confirmation whether this is the case.
- [ ] Confirm that there's a method to do this without the user having to hardcode their keys(env variables?)
- [ ] Test with DWS using their credentials.
- [ ] Add instructions to the s3 connector readme.md showing users how to leverage their own keys with the provided connector.
```

**Comment by masih** [comment]
Should this issue move to the s3-connector repo?

**Comment by masih** [comment]
Closing as duplicate of https://github.com/filecoin-project/motion-s3-connector/issues/3
