### ISSUE TITLE
[Feature] Motion Storage API that support deal prep and deal making in Filecoin (with Singularity integration)

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/motion#62]
This issue tracks all tickets required to integrate singularity for deal making for M2.0
```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/motion/issues/58
- [ ] https://github.com/filecoin-project/motion/issues/60
- [ ] https://github.com/filecoin-project/motion/issues/61
- [ ] https://github.com/filecoin-project/motion/issues/55
- [ ] https://github.com/filecoin-project/motion/issues/57
- [ ] https://github.com/filecoin-project/motion/issues/59
- [ ] https://github.com/filecoin-project/motion/issues/56
- [ ] https://github.com/filecoin-project/motion/issues/23
- [ ] https://github.com/filecoin-project/motion/issues/16
- [ ] https://github.com/filecoin-project/motion/issues/17
- [ ] https://github.com/filecoin-project/motion/issues/20
- [ ] https://github.com/filecoin-project/motion/pull/29
- [ ] https://github.com/filecoin-project/motion/issues/54
```

**Comment by masih** [comment]
@hannahhoward do we need/have an issue on Singularity replication that might be relevant to M2.0?

**Comment by masih** [comment]
All taks are done.closing.
