### ISSUE TITLE
Move Singularity To Use Swagger API

### ISSUE THREAD

**Issue by hannahhoward** [filecoin-project/motion#81]
# Goals

Rather than maintaining a handrolled API (https://github.com/data-preservation-programs/singularity/blob/main/client/client.go), we'd like to just use the auto-generated singularity Swagger API Client (https://github.com/data-preservation-programs/singularity/tree/main/client/swagger). This ticket is to attempt to remove custom API in Motion and move over to the Swagger API.

```[tasklist]
### Tasks
- [ ] modify motion command to always take an API when using singularity store (maybe make --experimentalSingularityStore a string arg instead of bool)
- [ ] initialize swagger client in main and pass to singularity blob store
- [ ] try to move over singularity blob store to use Swagger client
- [ ] fix or add API comments in Singularity to fix/add missing endpoints in autogenerated client code
```

### Acceptance Criteria

Either finish the conversion or write up problems encountered in attempting to do conversion as comment on this issue.
