### ISSUE TITLE
[Feature] Motion Retrieval API that support basic retrieval and status requests

### ISSUE THREAD

**Issue by celine3650** [filecoin-project/motion#86]
This issue tracks work needed to implement the retrieval API

```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/singularity/issues/113
- [ ] https://github.com/filecoin-project/motion/issues/111
- [ ] https://github.com/filecoin-project/motion/issues/112
- [ ] https://github.com/filecoin-project/motion/issues/103
```

**Comment by celine3650** [comment]
Fork from https://github.com/data-preservation-programs/singularity/issues/113
