### ISSUE TITLE
[Epic] Motion Alpha release

### ISSUE THREAD

**Issue by celine3650** [filecoin-project/motion#95]
ETA: 2023-09-31

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/motion/issues/97
- [ ] https://github.com/filecoin-project/motion/issues/62
- [ ] https://github.com/filecoin-project/motion/issues/96
- [ ] https://github.com/filecoin-project/motion/issues/86
- [ ] https://github.com/filecoin-project/motion/issues/49
- [ ] https://github.com/filecoin-project/motion/issues/93
```

**Comment by masih** [comment]
Removed bug issues and multipart upload support to beta. Closing.
